import type { Metadata } from "next";
import { Overpass, Overpass_Mono } from "next/font/google";
import { Providers } from './providers'
import Navbar from "./navbar";
import "./globals.css";
import ThemeSwitcher from "./_components/ThemeSwitcher";

const overpass = Overpass({
  subsets: ["latin"],
  variable: "--font-overpass",
});

const overpassMono = Overpass_Mono({
  subsets: ["latin"],
  variable: "--font-overpass-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${overpass.variable} ${overpassMono.variable} antialiased font-overpass`}
      >
        <Providers>
          <div className="dark:bg-slate-800 dark:text-slate-200 bg-slate-200 text-slate-900 transition-colors ease-in-out duration-500 min-h-screen flex flex-col">
          <Navbar />
          {children}
          <div className="fixed rounded-tl-3xl bg-slate-800 dark:bg-slate-200 text-slate-200 dark:text-slate-800 bottom-0 p-2 right-0 w-12 transition-colors duration-500 ease-in-out">
            <ThemeSwitcher />
          </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
